### PR TITLE
install dev controller

### PR DESCRIPTION
**Pull request by foxriver76**
as far as i can see, there the module is not accessing controller functionalities and thus this should be the only necessary change

### CODE REVIEW

**Comment by Apollon77** [comment]
... and we also need it then as 1.3.2 or 1.4.0 against https://github.com/ioBroker/testing/commit/29e317ef49079b5a4725060637b881fe25aab529 (I assume)

**Comment by Apollon77** [comment]
LGTM

**Review by AlCalzone — APPROVED** [review]
I **think** that is enough.

**Comment by Apollon77** [comment]
@AlCalzone whe the tests are installed via "npm ci" then the new version of testing (when we release) is not used automatically or?! but latest after merge

**Comment by AlCalzone** [comment]
npm ci installs the one in package-lock.json, so no.

**Pull request merged**
