### PR TITLE
fix message for title containing adapter/iobroker

### PR DESCRIPTION
**Pull request by foxriver76**
- Message was misleading

Edited only, so rebuild still needs to be done or editing build file.

### CODE REVIEW

**Comment by AlCalzone** [comment]
By that logic, the other messages should also be changed to include "should", correct?

**Comment by foxriver76** [comment]
Which other messages w.r.t. the topic do you mean?

**Comment by foxriver76** [comment]
The problem here is, that the message says that the title should contain the words "ioBroker" and "adapter" but it has to say, that it should not contain these words, because its obviously an ioBroker adapter. While taking a short look inside the code I don't see any other test where this is relevant.

**Comment by AlCalzone** [comment]
Hmm? Your commit changed the message from "it does not" to "it should not".

**Comment by foxriver76** [comment]
Maybe I interpreted the your error messages wrong. So your errors seem to tell how it is correct and now how it is in the adapter at the moment. When the test fails with 'The title does not contain adapter or iobroker' I interpreted it like, my adapter is missing the word adapter or iobroker in it. But when I look at your other messages it is consistent with this behavior, so closing this.

**Comment by AlCalzone** [comment]
Yes, those are not error messages. They describe expectations that are being tested.

**Comment by foxriver76** [comment]
thanks for explanaition. Was confused while testing are foreign repo and the message popped up ;-)

**Pull request closed without merging**
