### PR TITLE
Fix for #589: Update README.md

### PR DESCRIPTION
**Pull request by ANierbeck**
the test function needs to call the done method, otherwise tests always fail

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
We should investigate why the original code isn't working for you. Returning a promise is the modern alternative to using `done()`.

This change is not the way to do it.

**Comment by Apollon77** [comment]
@ANierbeck Please provide more details or maybe a link to your tests where it does not work

**Comment by AlCalzone** [comment]
See #589

**Comment by ANierbeck** [comment]
See comment in #589, let's ignore this

**Pull request closed without merging**
