### PR TITLE
Check for common.licenseInformation

### PR DESCRIPTION
**Pull request by klein0r**
- https://github.com/ioBroker/testing/issues/592

### CODE REVIEW

**Comment by klein0r** [comment]
Like this @foxriver76 ?

**Comment by foxriver76** [comment]
LGTM, but will of course fail if new attribute not provided, but if someone touches adapter should not hurt. 

Question is if this is used by RepoChecker, then it would be annoying, because not urgent  @mcm1957 do you know details?

**Comment by klein0r** [comment]
> but will of course fail if new attribute not provided

Like the schema check for io-package 😄

**Comment by mcm1957** [comment]
@AlCalzone 
**PLEASE DO NOT MERGE** in this variant

**The check MUST NOT fail if new attribute is missing.**
**The check MUST pass if EITHER license OR licenseInformation (and possible both of them) are present.**

Otherwise every dependabot PR will fail for older adapters.
And every small change will cause the tests to fail.
I will not be able to releases without additional effort new versions as tests will fail.

@Apollon77 
As far as I remember the discussion yesterday devs MUST NOT Be forced to adapt io-package.json in the very near future as this has no benefit for free adapters at all and will only cause devs to be frustrated.

**Comment by klein0r** [comment]
> **The check MUST NOT fail if new attribute is missing.** **The check MUST pass if EITHER license OR licenseInformation (and possible both of them) are present.**

In that case the schema should also be valid if one of the attributes is configured. At the moment `licenseInformation` is a required attribute and my IDE complains about the missing attribute... So I've changed it and removed the deprecated attribute.

Now all tests of all my adapters fail and I provided this PR which matches the schema of io-package (removed a deprecated attribute and check for the required attribute)...

**Comment by klein0r** [comment]
In my opinion the schema is the leading instance here and all other processes (create-adapter, repochecker, testing, ...) have to follow that definition.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
This would break tests for all existing adapters - unlike the schema check in VSCode, which you can choose to ignore.

Until `license` is removed from `js-controller` or admin, we should enforce that at least one of `license` or `licenseInformation` exists.

**Comment by klein0r** [comment]
Ok then I'll wait for the official solution

**Comment by mcm1957** [comment]
> Ok then I'll wait for the official solution

I've reached Dominic. He hoipefully will have a look at it this evening.

**Comment by AlCalzone** [comment]
Happy to merge your PR if you modify it :)
That will probably be quicker than doing it myself.

**Pull request closed without merging**
