### PR TITLE
fix: migrate to separate DB server/client instances, install controller and adapters separately

### PR DESCRIPTION
**Pull request by AlCalzone**
With this PR, we no longer edit the DB files directly to update/modify the DB, but rather spin up a client instance of the current DB type which is used to edit states and objects. This also adds support for the JSONL-DB.

Note that we still hardcode the DB paths in order to be able to do a quick backup/restore between test runs.

I did a little refactoring to keep the DB instances entirely in `DBConnection`, which also provides typed helper methods to access them. Those types are based on the adapter typings though - ideally, they should come directly from the DB classes.

fixes: #374 
fixes: #459
fixes: #466

### CODE REVIEW

**Comment by Apollon77** [comment]
basically correct for the "minimum way"

**Comment by AlCalzone** [comment]
Converting back to draft:
grafik

we have a hard dependency on js-controller now - that isn't good.

**Comment by AlCalzone** [comment]
PR is updated to also support JSONL.

I did test runs locally, twice without `CI=true` and twice with (after deleting the directory), then once without again. The logs showed `jsonl, jsonl, file, file, jsonl` for the runs, so both before and after migration this works.

**Review by AlCalzone — COMMENTED** [review]
~~This breaks https://github.com/ioBroker/ioBroker.lovelace/blob/master/test/integrationTests/testTools.js#L50, need to revisit.~~

Edit: resolved!

**Pull request merged**
