### PR TITLE
add EXIT_CODES to mockAdapterCore

### LINKED ISSUE #341: EXIT_CODES missing from mockAdapterCore
The member EXIT_CODES is missing from mockAdapter, which crashes adapters that use this feature.
In the original adapter it is added like this: 
https://github.com/ioBroker/adapter-core/blob/master/src/index.ts#L32

Adding 
```EXIT_CODES: Object.freeze(Object.assign({}, require(path.join(controllerDir, "lib/exitCodes.js"))))```
here https://github.com/ioBroker/testing/blob/master/src/tests/unit/mocks/mockAdapterCore.ts#L77 did solve the issue for me.

### PR DESCRIPTION
**Pull request by Garfonso**
should fix #341

### CODE REVIEW

**Comment by AlCalzone** [comment]
Did you test if this actually works? I wouldn't assume the js-controller directory to exist in unit tests since nothing is automatically set up.
https://github.com/ioBroker/testing/blob/d01a497ce0f4289ad376666f653f82b30dfbfb2b/src/tests/unit/mocks/mockAdapterCore.ts#L21-L24

**Comment by Garfonso** [comment]
It works locally, but I already have a js-controller dir from my permanent test environment... hm.

How can the user make sure it exists? Maybe there is a completely different way to solve the other issue, too?

**Comment by AlCalzone** [comment]
There should be an example for mocking tools.js, maybe that helps. Or just disable the unit test altogether.

**Comment by Garfonso** [comment]
> There should be an example for mocking tools.js, maybe that helps. Or just disable the unit test altogether.

The example for tools.js helped with the letsencrypt issue. 
But here it won't help, because tools.js and letsencrypt.js need to be required by the adapter seperately. But EXIT_CODES is a member of adapter-core and if I understand [this](https://github.com/ioBroker/testing/blob/master/src/tests/unit/harness/startMockAdapter.ts#L76) correctly, then, even if I try to mock adapter-core myself, it would be overwritten during adapter start anyway. So from my point of view either EXIT_CODES needs to be moved out of adapter-core or needs to be mocked in adapter-core. 😦

**Comment by AlCalzone** [comment]
Converting this to a draft PR until I'm sure how to proceed with unit tests and startup.

**Comment by AlCalzone** [comment]
This should no longer be necessary. We removed startup unit tests in the last update.

**Pull request closed without merging**
